name: flutter_rfid_uhf_sts
description: "This project is STS's Flutter plug-in for RFID UHF."
version: 0.0.7
homepage: https://github.com/DuaneDuan

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.softtechsystems.rfid.flutter_rfid_uhf_sts
        pluginClass: FlutterRfidUhfStsPlugin
